volumes:
  mongo_data: { }

networks:
  fast-api-oauth:
    driver: bridge

services:

  mongo:
    image: mongo:7.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "example"
      MONGO_INITDB_USER: "mongodb"
      MONGO_INITDB_PWD: "mongodb"
      KEYFILE_PATH: "/keyfile/keyfile"
      REPLICA_SET_HOST: "fast-api-oauth-mongo-1"
      REPLICA_SET_PORT: "27017"
    command: [ "--replSet", "rs0", "--keyFile", "/keyfile/keyfile", "--bind_ip", "localhost,fast-api-oauth-mongo-1" ]
    healthcheck:
      test: echo "try { rs.status() } catch (err) { rs.initiate({_id:'rs0',members:[{_id:0,host:'fast-api-oauth-mongo-1:27017'}]}) }" | mongosh -u $$MONGO_INITDB_ROOT_USERNAME -p $$MONGO_INITDB_ROOT_PASSWORD --port 27017 --quiet
      interval: 5s
      timeout: 30s
      start_period: 0s
      start_interval: 1s
      retries: 30
    volumes:
      - mongo_data:/data/db
      - .provisions/docker/mongo/keyfile/:/keyfile/:wro
      - .provisions/docker/mongo/mongo-init-js/:/docker-entrypoint-initdb.d/:ro
    ports:
      - "27017:27017"
    networks:
      - fast-api-oauth

  mailhog:
    image: mailhog/mailhog:v1.0.0
    ports:
      - "8025:8025"
    networks:
      - fast-api-oauth

  fast-api: &fast-api
    build:
      context: .
      dockerfile: .provisions/docker/fast-api/dev/Dockerfile
    volumes:
      - .:/var/app:z
      - .provisions/docker-fast-api-startup-script/:/docker-startup-script
    env_file:
      - .env
    depends_on:
      - mongo
    ports:
      - "8080:8080"
    networks:
      - fast-api-oauth
